### PR TITLE
Add "com.sun.activation" % "javax.activation" for Java9+

### PR DESCRIPTION
**Pull request by er1c**

### CODE REVIEW

**Review by jvican — APPROVED** [review]
LGTM, thanks :+1:

**Comment by jvican** [comment]
BTW, is this problematic if you run it on a non Java 9 runtime? @er1c

**Comment by er1c** [comment]
@jvican short answer is no, you can see the current java8 tests passing: https://travis-ci.org/scalacenter/compiler-benchmark/builds/524537907?utm_source=github_status&utm_medium=notification

It's the same dependency, they just stopped including it in the JDK (https://blog.codefx.org/java/java-9-migration-guide/)

**Comment by jvican** [comment]
Thank you @er1c

**Pull request merged**
